DROP TABLE IF EXISTS flashcard;
DROP TABLE IF EXISTS learn_set;
DROP TABLE IF EXISTS question;
DROP TABLE IF EXISTS quiz;
DROP TABLE IF EXISTS subjects;
DROP TABLE IF EXISTS folder;
DROP TABLE IF EXISTS user;